# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:04:52+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class RequestMethod(Enum):
    HEAD = 'HEAD'
    GET = 'GET'
    POST = 'POST'
    PATCH = 'PATCH'
    PUT = 'PUT'
    DELETE = 'DELETE'


class MonitorV1Alert(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Alert resource.',
    )
    alert_text: Optional[str] = Field(None, description='The text of the alert.')
    api_version: Optional[str] = Field(
        None,
        description="The API version used when the alert was generated.  Can be empty for events that don't have a specific API version.",
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_generated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the alert was generated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#UTC) format.  Due to buffering, this can be different than `date_created`.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    error_code: Optional[str] = Field(
        None,
        description='The error code for the condition that generated the alert. See the [Error Dictionary](https://www.twilio.com/docs/api/errors) for possible causes and solutions to the error.',
    )
    log_level: Optional[str] = Field(
        None,
        description='The log level.  Can be: `error`, `warning`, `notice`, or `debug`.',
    )
    more_info: Optional[str] = Field(
        None,
        description='The URL of the page in our [Error Dictionary](https://www.twilio.com/docs/api/errors) with more information about the error condition.',
    )
    request_method: Optional[RequestMethod] = Field(
        None,
        description='The method used by the request that generated the alert. If the alert was generated by a request we made to your server, this is the method we used. If the alert was generated by a request from your application to our API, this is the method your application used.',
    )
    request_url: Optional[str] = Field(
        None,
        description='The URL of the request that generated the alert. If the alert was generated by a request we made to your server, this is the URL on your server that generated the alert. If the alert was generated by a request from your application to our API, this is the URL of the resource requested.',
    )
    resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the resource for which the alert was generated.  For instance, if your server failed to respond to an HTTP request during the flow of a particular call, this value would be the SID of the server.  This value is empty if the alert was not generated for a particular resource.',
    )
    service_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the service or resource that generated the alert. Can be `null`.',
    )
    sid: Optional[
        constr(pattern=r'^NO[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Alert resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Alert resource.'
    )


class MonitorV1AlertInstance(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Alert resource.',
    )
    alert_text: Optional[str] = Field(None, description='The text of the alert.')
    api_version: Optional[str] = Field(
        None,
        description="The API version used when the alert was generated.  Can be empty for events that don't have a specific API version.",
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_generated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the alert was generated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#UTC) format.  Due to buffering, this can be different than `date_created`.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    error_code: Optional[str] = Field(
        None,
        description='The error code for the condition that generated the alert. See the [Error Dictionary](https://www.twilio.com/docs/api/errors) for possible causes and solutions to the error.',
    )
    log_level: Optional[str] = Field(
        None,
        description='The log level.  Can be: `error`, `warning`, `notice`, or `debug`.',
    )
    more_info: Optional[str] = Field(
        None,
        description='The URL of the page in our [Error Dictionary](https://www.twilio.com/docs/api/errors) with more information about the error condition.',
    )
    request_headers: Optional[str] = Field(
        None,
        description='The request headers of the request that generated the alert. This value is only returned when a single Alert resource is fetched.',
    )
    request_method: Optional[RequestMethod] = Field(
        None,
        description='The method used by the request that generated the alert. If the alert was generated by a request we made to your server, this is the method we used. If the alert was generated by a request from your application to our API, this is the method your application used.',
    )
    request_url: Optional[str] = Field(
        None,
        description='The URL of the request that generated the alert. If the alert was generated by a request we made to your server, this is the URL on your server that generated the alert. If the alert was generated by a request from your application to our API, this is the URL of the resource requested.',
    )
    request_variables: Optional[str] = Field(
        None,
        description='The variables passed in the request that generated the alert. This value is only returned when a single Alert resource is fetched.',
    )
    resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the resource for which the alert was generated.  For instance, if your server failed to respond to an HTTP request during the flow of a particular call, this value would be the SID of the server.  This value is empty if the alert was not generated for a particular resource.',
    )
    response_body: Optional[str] = Field(
        None,
        description='The response body of the request that generated the alert. This value is only returned when a single Alert resource is fetched.',
    )
    response_headers: Optional[str] = Field(
        None,
        description='The response headers of the request that generated the alert. This value is only returned when a single Alert resource is fetched.',
    )
    service_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the service or resource that generated the alert. Can be `null`.',
    )
    sid: Optional[
        constr(pattern=r'^NO[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Alert resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Alert resource.'
    )


class MonitorV1Event(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Event resource.',
    )
    actor_sid: Optional[
        constr(pattern=r'^US[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the actor that caused the event, if available. Can be `null`.',
    )
    actor_type: Optional[str] = Field(
        None,
        description='The type of actor that caused the event. Can be: `user` for a change made by a logged-in user in the Twilio Console, `account` for an event caused by an API request by an authenticating Account, `twilio-admin` for an event caused by a Twilio employee, and so on.',
    )
    description: Optional[str] = Field(
        None, description='A description of the event. Can be `null`.'
    )
    event_data: Optional[Any] = Field(
        None,
        description='An object with additional data about the event. The  contents depend on `event_type`. For example, event-types of the form `RESOURCE.updated`, this value contains a `resource_properties` dictionary that describes the previous and updated properties of the resource.',
    )
    event_date: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the event was recorded specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    event_type: Optional[str] = Field(
        None,
        description="The event's type. Event-types are typically in the form: `RESOURCE_TYPE.ACTION`, where `RESOURCE_TYPE` is the type of resource that was affected and `ACTION` is what happened to it. For example, `phone-number.created`. For a full list of all event-types, see the [Monitor Event Types](https://www.twilio.com/docs/usage/monitor-events#event-types).",
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='The absolute URLs of related resources.'
    )
    resource_sid: Optional[
        constr(pattern=r'^[a-zA-Z]{2}[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='The SID of the resource that was affected.')
    resource_type: Optional[str] = Field(
        None,
        description='The type of resource that was affected. For a full list of all resource-types, see the [Monitor Event Types](https://www.twilio.com/docs/usage/monitor-events#event-types).',
    )
    sid: Optional[
        constr(pattern=r'^AE[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Event resource.',
    )
    source: Optional[str] = Field(
        None,
        description='The originating system or interface that caused the event.  Can be: `web` for events caused by user action in the Twilio Console, `api` for events caused by a request to our API, or   `twilio` for events caused by an automated or internal Twilio system.',
    )
    source_ip_address: Optional[str] = Field(
        None,
        description='The IP address of the source, if the source is outside the Twilio cloud. This value is `null` for events with `source` of `twilio`',
    )
    url: Optional[AnyUrl] = Field(
        None,
        description='The absolute URL of the resource that was affected. Can be `null`.',
    )


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1AlertsGetResponse(BaseModel):
    alerts: Optional[List[MonitorV1Alert]] = None
    meta: Optional[Meta] = None


class V1EventsGetResponse(BaseModel):
    events: Optional[List[MonitorV1Event]] = None
    meta: Optional[Meta] = None
